# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 23:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bierlijst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_bier', models.IntegerField(default=0)),
                ('sum_wwijn', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sum_rwijn', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_bier', models.IntegerField(default=0)),
                ('total_wwijn', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_rwijn', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='turf',
            name='turf_beer',
        ),
        migrations.AlterField(
            model_name='turf',
            name='turf_count',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
    ]
