# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 23:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bierlijst', '0003_auto_20160301_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summation',
            name='id',
        ),
        # migrations.AlterField(
        #   model_name='summation',
        #    name='user',
        #    field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        #),
    ]
