# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bierlijst', '0004_auto_20160301_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Summation',
        ),
    ]
