# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bierlijst', '0005_auto_20160301_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='turf_count',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
