# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bierlijst', '0006_auto_20160302_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='turf_by',
            field=models.CharField(default='fill', max_length=30),
            preserve_default=False,
        ),
    ]
