# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bierlijst', '0007_turf_turf_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf',
            old_name='turf_user',
            new_name='turf_user_id',
        ),
        migrations.AddField(
            model_name='turf',
            name='turf_to',
            field=models.CharField(default='fill', max_length=30),
            preserve_default=False,
        ),
    ]
