# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bierlijst', '0008_auto_20160302_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boete',
            old_name='time_opened',
            new_name='created_time',
        ),
        migrations.RemoveField(
            model_name='boete',
            name='boete_open',
        ),
        migrations.RemoveField(
            model_name='boete',
            name='time_closed',
        ),
        migrations.AddField(
            model_name='boete',
            name='boete_value',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='boete',
            name='created_by',
            field=models.CharField(default='fill', max_length=30),
            preserve_default=False,
        ),
    ]
