# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bierlijst', '0009_auto_20160303_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='turf_note',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
