# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bierlijst', '0010_turf_turf_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='boete',
            name='boete_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
