# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bierlijst', '0011_boete_boete_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boete',
            old_name='boete_value',
            new_name='boete_count',
        ),
    ]
