# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bierlijst', '0013_streamingtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='streamingtoken',
            name='token_user',
        ),
        migrations.DeleteModel(
            name='StreamingToken',
        ),
    ]
