# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-09 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bierlijst', '0014_auto_20160422_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boete',
            name='boete_note',
            field=models.CharField(max_length=100),
        ),
    ]
