# Generated by Django 2.1.9 on 2019-07-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bierlijst', '0015_auto_20161009_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf',
            old_name='turf_user_id',
            new_name='turf_user',
        ),
    ]
