# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 21:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bal_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('bal_amount', models.DecimalField(decimal_places=4, max_digits=7)),
                ('bal_type', models.CharField(max_length=10)),
                ('bal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_date', models.DateField(default=django.utils.timezone.now)),
                ('list_open', models.BooleanField(default=True)),
                ('list_cost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('list_date', models.DateField()),
                ('list_cook', models.BooleanField(default=False)),
                ('list_count', models.IntegerField()),
                ('list_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
