# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eetlijst', '0003_auto_20160309_2107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HO',
            new_name='HOLog',
        ),
    ]
