# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eetlijst', '0005_auto_20160311_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='datelist',
            name='num_eating',
            field=models.IntegerField(default=0),
        ),
    ]
