# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eetlijst', '0006_datelist_num_eating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='list_cost',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
