# Generated by Django 2.1.8 on 2019-06-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eetlijst', '0008_holog_total_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='datelist',
            name='eta_time',
            field=models.DateTimeField(null=True),
        ),
    ]
