# Generated by Django 2.1.9 on 2019-07-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eetlijst', '0010_userdinner_dinner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdinner',
            old_name='list_count',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='userdinner',
            old_name='list_date',
            new_name='dinner_date',
        ),
        migrations.RenameField(
            model_name='userdinner',
            old_name='list_cook',
            new_name='is_cook',
        ),
        migrations.RenameField(
            model_name='userdinner',
            old_name='list_cost',
            new_name='split_cost',
        ),
    ]
