# Generated by Django 2.1.9 on 2019-07-14 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eetlijst', '0011_auto_20190704_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinner',
            old_name='signup_time',
            new_name='cook_signup_time',
        ),
    ]
