# Generated by Django 2.1.9 on 2019-07-16 14:37

from django.db import migrations, models
from django.db.migrations import RunPython


class Migration(migrations.Migration):

    def init_cost_time(apps, _):
        Dinner = apps.get_model('eetlijst', 'Dinner')
        dinners = Dinner.objects.all()

        for dinner in dinners:
            if dinner.cost and dinner.cost_time is None:
                dinner.cost_time = dinner.close_time
            dinner.save()



    dependencies = [
        ('eetlijst', '0012_auto_20190714_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='cost_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(init_cost_time, reverse_code=RunPython.noop)
    ]
