# Generated by Django 2.1.9 on 2019-07-25 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('eetlijst', '0014_auto_20190716_2055'),
        ('user', '0020_auto_20190211_1851'),
    ]

    def init_transfer_users(apps, _):
        Transfer = apps.get_model('eetlijst', 'Transfer')
        Housemate = apps.get_model('user', 'Housemate')
        transfers = Transfer.objects.all()

        custom_matches = {'Balls': 'Dale',
                          'Mattias': 'Wimpler',
                          'Emile': 'Emilio'}

        for transfer in transfers:
            try:
                transfer.from_user_temp = Housemate.objects.get(display_name__iexact=transfer.from_user).user
            except Exception:
                if transfer.from_user in custom_matches:
                    transfer.from_user_temp = Housemate.objects.get(
                        display_name__iexact=custom_matches[transfer.from_user]).user
                else:
                    print("The Housemate {hm} does not exist. Fix this by adding a matching name.".format(
                        hm=transfer.from_user))
                    exit('Quit migration.')

            try:
                transfer.to_user_temp = Housemate.objects.get(display_name__iexact=transfer.to_user).user
            except Exception:
                if transfer.to_user in custom_matches:
                    transfer.to_user_temp = Housemate.objects.get(
                        display_name__iexact=custom_matches[transfer.to_user]).user
                else:
                    print("The Housemate {hm} does not exist. Fix this by adding a matching name.".format(
                        hm=transfer.to_user))
                    exit('Quit migration.')
            transfer.save()

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='from_user_temp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from_transfer',
                                    to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='transfer',
            name='to_user_temp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_transfer',
                                    to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.RunPython(init_transfer_users),
        migrations.RemoveField(
            model_name='transfer',
            name='to_user'
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='from_user'
        ),
        migrations.RenameField(
            model_name='transfer',
            old_name='from_user_temp',
            new_name='from_user'),
        migrations.RenameField(
            model_name='transfer',
            old_name='to_user_temp',
            new_name='to_user'),
        migrations.AlterField(
            model_name='transfer',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_transfer',
                                    to=settings.AUTH_USER_MODEL)),
        migrations.AlterField(
            model_name='transfer',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_from_transfer',
                                    to=settings.AUTH_USER_MODEL))
    ]
