# Generated by Django 2.1.9 on 2019-07-24 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eetlijst', '0014_auto_20190716_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eetlijst.Transfer'),
        ),
    ]
