# Generated by Django 2.1.9 on 2019-07-28 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_user', models.BooleanField(null=True)),
                ('accepted_time', models.BooleanField(null=True)),
                ('upload_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_user', models.DecimalField(decimal_places=2, max_digits=5)),
                ('affected_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.Receipt')),
            ],
        ),
    ]
