# Generated by Django 2.1.9 on 2019-07-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keukendienst',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='keukendienst',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
