# Generated by Django 2.1.11 on 2019-08-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_receipt_receiptcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_title',
            field=models.CharField(default='Unknown title', max_length=100),
        ),
    ]
