# Generated by Django 2.1.11 on 2019-09-01 22:23

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_auto_20190830_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='accepted',
            field=models.NullBooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='accepted_time',
        ),
        migrations.AddField(
            model_name='receipt',
            name='accepted_time',
            field=models.DateTimeField(null=True),
        ),
    ]
