# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-03 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesau', '0012_auto_20170330_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='report_path',
            new_name='report_file',
        ),
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=models.FileField(upload_to='hr_reports/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
