# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 11:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesau', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('thesau_approval', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('note', models.CharField(blank=True, max_length=50)),
                ('submit_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_balance', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('hr_boetes', models.IntegerField(default=0)),
                ('hr_bier', models.IntegerField(default=0)),
                ('hr_wwijn', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('hr_rwijn', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_time',
        ),
        migrations.AddField(
            model_name='report',
            name='report_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='report',
            name='report_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesau.Report'),
        ),
        migrations.AddField(
            model_name='userreport',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
