# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesau', '0003_paymentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsreport',
            name='exclude_users',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
