# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesau', '0004_itemsreport_exclude_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentreport',
            name='payment_user',
        ),
        migrations.RemoveField(
            model_name='itemsreport',
            name='exclude_users',
        ),
        migrations.RemoveField(
            model_name='itemsreport',
            name='thesau_approval',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_open',
        ),
        migrations.RemoveField(
            model_name='userreport',
            name='hr_balance',
        ),
        migrations.AddField(
            model_name='itemsreport',
            name='approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='bier_lost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='bier_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='bier_purchased',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='bier_stock_in',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='bier_stock_out',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='bier_turfed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='rwijn_lost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='rwijn_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='rwijn_purchased',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='rwijn_stock_in',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='rwijn_stock_out',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='rwijn_turfed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='wwijn_lost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='wwijn_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='wwijn_purchased',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='wwijn_stock_in',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='wwijn_stock_out',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='wwijn_turfed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userreport',
            name='eetlijst_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='PaymentReport',
        ),
    ]
