# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesau', '0005_auto_20160405_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsreport',
            name='open',
            field=models.BooleanField(default=True),
        ),
    ]
