# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesau', '0006_itemsreport_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='bier_lost',
        ),
        migrations.RemoveField(
            model_name='report',
            name='bier_price',
        ),
        migrations.RemoveField(
            model_name='report',
            name='bier_purchased',
        ),
        migrations.RemoveField(
            model_name='report',
            name='bier_stock_in',
        ),
        migrations.RemoveField(
            model_name='report',
            name='bier_stock_out',
        ),
        migrations.RemoveField(
            model_name='report',
            name='bier_turfed',
        ),
        migrations.RemoveField(
            model_name='report',
            name='rwijn_lost',
        ),
        migrations.RemoveField(
            model_name='report',
            name='rwijn_price',
        ),
        migrations.RemoveField(
            model_name='report',
            name='rwijn_purchased',
        ),
        migrations.RemoveField(
            model_name='report',
            name='rwijn_stock_in',
        ),
        migrations.RemoveField(
            model_name='report',
            name='rwijn_stock_out',
        ),
        migrations.RemoveField(
            model_name='report',
            name='rwijn_turfed',
        ),
        migrations.RemoveField(
            model_name='report',
            name='wwijn_lost',
        ),
        migrations.RemoveField(
            model_name='report',
            name='wwijn_price',
        ),
        migrations.RemoveField(
            model_name='report',
            name='wwijn_purchased',
        ),
        migrations.RemoveField(
            model_name='report',
            name='wwijn_stock_in',
        ),
        migrations.RemoveField(
            model_name='report',
            name='wwijn_stock_out',
        ),
        migrations.RemoveField(
            model_name='report',
            name='wwijn_turfed',
        ),
        migrations.AddField(
            model_name='report',
            name='report_name',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
