# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesau', '0007_auto_20160405_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoetesReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boete_wwijn', models.IntegerField(default=0)),
                ('boete_rwijn', models.IntegerField(default=0)),
            ],
        ),
    ]
