# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesau', '0008_boetesreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boetesreport',
            old_name='boete_rwijn',
            new_name='boete_count',
        ),
        migrations.RemoveField(
            model_name='boetesreport',
            name='boete_wwijn',
        ),
        migrations.AddField(
            model_name='boetesreport',
            name='type',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
