# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesau', '0009_auto_20160422_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_path',
            field=models.CharField(default='hr_reports/HR_2016_april.xlsx', max_length=50),
            preserve_default=False,
        ),
    ]
