# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thesau', '0010_report_report_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsreport',
            name='submit_user',
        ),
        migrations.DeleteModel(
            name='ItemsReport',
        ),
    ]
