# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-07 16:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_iban.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesau', '0011_auto_20160422_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutationsFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField(default=None)),
                ('upload_date', models.DateField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='bank_uploads/%Y/%m/%d')),
                ('upload_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MutationsParsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField(default=None)),
                ('start_balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('end_balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('source_IBAN', django_iban.fields.IBANField(enforce_database_constraint=True, max_length=34)),
                ('mutation_date', models.DateField(null=True)),
                ('mutation_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesau.MutationsFiles')),
            ],
        ),
    ]
