# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-24 19:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_iban.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thesau', '0011_auto_20160422_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='MutationsFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sta_file', models.FileField(upload_to='bank_uploads/%Y/%m/%d')),
                ('num_mutations', models.IntegerField(default=0)),
                ('num_duplicates', models.IntegerField(default=0)),
                ('applied', models.BooleanField(default=False)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesau.Report')),
                ('upload_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MutationsParsed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('end_balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('source_IBAN', django_iban.fields.IBANField(enforce_database_constraint=True, max_length=34)),
                ('dest_IBAN', django_iban.fields.IBANField(enforce_database_constraint=True, max_length=34)),
                ('mutation_date', models.DateField(null=True)),
                ('mutation_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesau.MutationsFile')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thesau.Report')),
            ],
        ),
    ]
