# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesau', '0011_auto_20160422_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreport',
            old_name='hr_boetes',
            new_name='hr_boete_rwijn',
        ),
        migrations.AddField(
            model_name='userreport',
            name='hr_boete_wwijn',
            field=models.IntegerField(default=0),
        ),
    ]
