# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-25 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesau', '0012_mutationsfile_mutationsparsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_closed',
            field=models.BooleanField(default=False),
        ),
    ]
