# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-04 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesau', '0013_auto_20170403_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mutationsfile',
            name='description',
        ),
        migrations.AddField(
            model_name='mutationsparsed',
            name='mutation_info',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='mutationsparsed',
            name='source_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
