# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-26 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesau', '0013_report_report_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='mutationsparsed',
            name='applied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mutationsparsed',
            name='transfer_type',
            field=models.CharField(default='D', max_length=1),
        ),
    ]
