# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemate',
            name='movein_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
