# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20160216_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemate',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
    ]
