# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_housemate_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemate',
            name='display_name',
            field=models.CharField(default='disp_name', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='housemate',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='housemate',
            name='cell_phone',
            field=models.CharField(default='06-', max_length=50),
        ),
        migrations.AlterField(
            model_name='housemate',
            name='parent_phone',
            field=models.CharField(default='06-', max_length=50),
        ),
    ]
