# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 18:06
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.auth.models import Group



class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20160229_1855'),
    ]

    operations = [
    ]
