# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20160229_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemate',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
