# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_housemate_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemate',
            name='sum_bier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='housemate',
            name='sum_rwijn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='housemate',
            name='sum_wwijn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='housemate',
            name='total_bier',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='housemate',
            name='total_rwijn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='housemate',
            name='total_wwijn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
