# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 01:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20160301_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemate',
            name='active',
        ),
    ]
