# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20160302_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housemate',
            old_name='boetes_sum',
            new_name='boetes_turfed',
        ),
    ]
