# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_housemate_allergies'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemate',
            name='moveout_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='housemate',
            name='moveout_set',
            field=models.NullBooleanField(),
        ),
    ]
