# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20160405_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housemate',
            old_name='allergies',
            new_name='diet',
        ),
    ]
