# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20160405_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemate',
            name='parent_phone',
            field=models.CharField(blank=True, default='06-', max_length=50),
        ),
    ]
