# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20160405_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemate',
            name='room_number',
            field=models.IntegerField(null=True),
        ),
    ]
