# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-28 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20160405_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housemate',
            old_name='boetes_turfed',
            new_name='boetes_geturfd',
        ),
        migrations.AlterField(
            model_name='housemate',
            name='cell_phone',
            field=models.CharField(default='06', max_length=50),
        ),
        migrations.AlterField(
            model_name='housemate',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
