# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20161113_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housemate',
            old_name='boetes_geturfd',
            new_name='boetes_geturfd_rwijn',
        ),
        migrations.AddField(
            model_name='housemate',
            name='boetes_geturfd_wwijn',
            field=models.IntegerField(default=0),
        ),
    ]
