# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-06 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20161113_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housemate',
            name='activate_date',
        ),
        migrations.RemoveField(
            model_name='housemate',
            name='inactivate_date',
        ),
    ]
