# Generated by Django 2.0.9 on 2019-02-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_housemate_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemate',
            name='diet',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
