# Generated by Django 2.1.9 on 2019-07-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20190211_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemate',
            name='diet',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
