# Generated by Django 2.1.9 on 2019-07-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20190726_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemate',
            name='sublet_date',
            field=models.DateField(null=True),
        ),
    ]
