# Generated by Django 2.1.9 on 2019-08-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_housemate_sublet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housemate',
            name='display_name',
            field=models.CharField(max_length=30),
        ),
    ]
