# Generated by Django 2.2.10 on 2020-02-25 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20190802_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='HousemateGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=1000)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('date_ended', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HousemateGroupLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now=True)),
                ('date_left', models.DateField(blank=True, null=True)),
                ('role_description', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.HousemateGroup')),
                ('housemate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Housemate')),
            ],
        ),
        migrations.AddField(
            model_name='housemategroup',
            name='groups',
            field=models.ManyToManyField(through='user.HousemateGroupLink', to='user.Housemate'),
        ),
    ]
