# Generated by Django 2.2.10 on 2020-04-14 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_snakehighscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snakehighscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
