# Generated by Django 2.2.10 on 2020-05-13 16:11

from django.db import migrations

def copy_field(apps, schema_editor):
    UserHighScoreModel = apps.get_model('user', 'SnakeHighScore')
    GameHighScoreModel = apps.get_model('game', 'SnakeHighScore')
    user_highscores = UserHighScoreModel.objects.all()
    for old_highscore in user_highscores:
        GameHighScoreModel.objects.create(
            user=old_highscore.user,
            nickname=old_highscore.nickname,
            score=old_highscore.score,
            time=old_highscore.time
        )

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_auto_20200414_2219'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(copy_field),
        migrations.DeleteModel(
            name='SnakeHighScore',
        ),
    ]
